spring:
  application:
    name: 'loja'
  cloud:
    config:
      fail-fast: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka   
