spring:
  application:
    name: 'fornecedor'
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
   url: jdbc:h2:mem:fornecedordb;DB_CLOSE_ON_EXIT=FALSE
   username: sa
   password: 
   driver-class-name: org.h2.Driver
   platform: h2 # dizer qual banco esta usando
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false    

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: Fornecedor
    description: Micro serviço de fornecedor
    version: 1.2.0
    encoding: UTF-8
    java:
      version: 11      
       