server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  config:
    #Spring Cloud Config Client, será necessário definir a spring.config.importpropriedade para vincular ao Config Server
    import: optional:configserver:http://localhost:8888?fail-fast=true #para importa algum arquivo de propriedade, ex.: developer.properties
  profiles:
    active: dev
  #cloud: já foi definido no import acima
    #config:
      #uri: http://localhost:8888
